{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Duration (P95)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_all_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Loop Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "nodejs_eventloop_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}